In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("survey_results_public.csv")
schema = pd.read_csv("survey_results_schema.csv")

C:\Users\sashk\AppData\Local\Temp\ipykernel_1120\2951978226.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("survey_results_public.csv")

In [3]:
schema.head(10)

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0

Завдання 1. Підрахунок загальної кількості респондентів

In [4]:
total_respondents = df.shape[0]
total_respondents

49191

Завдання 2. Аналіз повноти відповідей респондентів

In [5]:
schema_questions = set(schema["qname"])
len(schema_questions)

139

In [6]:
df_columns = set(df.columns)
len(df_columns)

172

In [7]:
common_questions = schema_questions.intersection(df_columns)
len(common_questions)

126

In [8]:
df_questions = df[list(common_questions)]
df_questions.shape

(49191, 126)

In [9]:
complete_respondents = df_questions.dropna()
complete_respondents.shape[0]

0

Завдання 3. Статистичний аналіз досвіду респондентів

In [10]:
df["WorkExp"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 49191 entries, 0 to 49190
Series name: WorkExp
Non-Null Count  Dtype
--------------  -----
42893 non-null  float64
dtypes: float64(1)
memory usage: 384.4 KB

In [11]:
mean_workexp = df["WorkExp"].mean()
median_workexp = df["WorkExp"].median()
mode_workexp = df["WorkExp"].mode()[0]
mean_workexp, median_workexp, mode_workexp

(np.float64(13.367402606485907), 10.0, np.float64(10.0))

In [12]:
workexp_stats = pd.Series({
    "Mean": mean_workexp,
    "Median": median_workexp,
    "Mode": mode_workexp
})
workexp_stats

Mean      13.367403
Median    10.000000
Mode      10.000000
dtype: float64

Завдання 4. Аналіз віддаленої роботи

In [13]:
schema[schema["question"].str.contains("work", case=False, na=False)]

,qid,qname,question,type,sub,sq_id
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN

In [14]:
df["RemoteWork"].value_counts(dropna=False)

RemoteWork
NaN                                                                             15411
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [15]:
remote_workers_count = (df["RemoteWork"] == "Remote").sum()
remote_workers_count

np.int64(10931)

Завдання 5. Визначення популярності Python

In [16]:
df["LanguageHaveWorkedWith"].head()

0                     Bash/Shell (all shells);Dart;SQL
1                                                 Java
2                  Dart;HTML/CSS;JavaScript;TypeScript
3                                      Java;Kotlin;SQL
4    C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
Name: LanguageHaveWorkedWith, dtype: object

In [17]:
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

In [18]:
python_users_count = python_users.sum()
python_users_count

np.int64(18466)

In [19]:
total_respondents = df.shape[0]
total_respondents

49191

In [20]:
python_percentage = (python_users_count / total_respondents) * 100
python_percentage

np.float64(37.53938728629221)

In [21]:
python_percentage_rounded = round(python_percentage, 1)
f"{python_percentage_rounded}%"

'37.5%'

Завдання 6. Аналіз шляхів навчання програмуванню

In [22]:
df["LearnCode"].head()

0    Online Courses or Certification (includes all ...
1    Online Courses or Certification (includes all ...
2    Online Courses or Certification (includes all ...
3    Other online resources (e.g. standard search, ...
4                                                  NaN
Name: LearnCode, dtype: object

In [23]:
df["LearnCode"].value_counts(dropna=False).head(10)

LearnCode
NaN                                                                                                                                                                                                                                                                                                    15635
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system)                                                                                                                                 632
Other online resources (e.g. standard search, forum, online community);Technical documentation (is generated for/by the tool or system)                                                                                                                                                                  465
Online Courses or Certification (includes all media types)                                                                                                                                                                                                                                               405
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps                                                                                             397
AI CodeGen tools or AI-enabled apps                                                                                                                                                                                                                                                                      387
Technical documentation (is generated for/by the tool or system)                                                                                                                                                                                                                                         336
Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps;Blogs or podcasts      315
Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Blogs or podcasts                                          290
Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps                        281
Name: count, dtype: int64

In [24]:
online_course_users = df["LearnCode"].str.contains("Online Courses", na=False)

In [25]:
online_course_users_count = online_course_users.sum()
online_course_users_count

np.int64(10973)

Завдання 7. Географічний аналіз компенсації Python-розробників

In [26]:
python_df = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]

In [27]:
python_df[["Country", "ConvertedCompYearly"]].head()

    Country  ConvertedCompYearly
4   Ukraine              60000.0
7   Ukraine              72000.0
8   Ukraine              70000.0
15    India                  NaN
17   Greece                  NaN

In [28]:
compensation_by_country = (
    python_df
    .groupby("Country")["ConvertedCompYearly"]
    .agg(
        mean_compensation="mean",
        median_compensation="median"
    )
    .reset_index()
)

compensation_by_country

,Country,mean_compensation,median_compensation
0,Afghanistan,22328.666667,1000.0
1,Albania,47217.600000,50000.0
2,Algeria,20187.285714,7088.0
3,Andorra,226103.500000,226103.5
4,Angola,NaN,NaN
...,...,...,...
162,"Venezuela, Bolivarian Republic of...",9908.647059,3000.0
163,Viet Nam,218837.166667,8254.0
164,Yemen,32929.500000,23672.0
165,Zambia,5424.250000,3206.0
166,Zimbabwe,34000.000000,25500.0

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [29]:
df[["ConvertedCompYearly", "EdLevel"]].head()

   ConvertedCompYearly                                          EdLevel
0              61256.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
1             104413.0              Associate degree (A.A., A.S., etc.)
2              53061.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
3              36197.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
4              60000.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

In [30]:
df_sorted = df.sort_values(
    by="ConvertedCompYearly",
    ascending=False
)

In [31]:
top5_paid = df_sorted.head(5)

In [32]:
top5_paid[["ConvertedCompYearly", "EdLevel"]]

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)